#!/usr/bin/env bash
# android-rebuild import — nixos-generate-config for phones. READ-ONLY.
# Reads a connected device's user-app inventory (with installer attribution)
# and emits a starter device.nix on stdout. Curate before converging: verify
# f-droid packages actually live on f-droid.org (update-lock errors loudly if
# not — e.g. IzzyOnDroid apps), and fill in the github= stubs.
set -euo pipefail

serial=${ANDROID_SERIAL:-}
while [ $# -gt 0 ]; do
  case $1 in
  --serial) serial=$2; shift 2 ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
adb=(adb)
[ -n "$serial" ] && adb=(adb -s "$serial")

model=$("${adb[@]}" shell getprop ro.product.model | tr -d '\r')
abi=$("${adb[@]}" shell getprop ro.product.cpu.abi | tr -d '\r')
inv=$("${adb[@]}" shell pm list packages -3 -i --user 0 | tr -d '\r')

fdroid=() release=() attended=() unknown=()
while read -r line; do
  pkg=$(sed -n 's/^package:\([^ ]*\) .*/\1/p' <<<"$line")
  [ -n "$pkg" ] || continue
  installer=$(sed -n 's/.*installer=\(.*\)$/\1/p' <<<"$line")
  case $installer in
  org.fdroid.fdroid | org.fdroid.basic | com.looker.droidify | com.machiav3lli.fdroid)
    fdroid+=("$pkg") ;;
  com.aurora.store | com.android.vending)
    attended+=("$pkg") ;;
  dev.imranr.obtainium | dev.imranr.obtainium.fdroid)
    release+=("$pkg") ;;
  *)
    unknown+=("$pkg installer=$installer") ;;
  esac
done <<<"$inv"

cat <<EOF
# Generated by android-rebuild import — $model, $(date -I 2>/dev/null || true)
# CURATE BEFORE CONVERGING. Notes:
#  - fdroid list: entries not on f-droid.org (e.g. IzzyOnDroid) will fail
#    'android-rebuild update' loudly — move those to apps.release or attended.
#  - release entries need their github = "owner/repo" filled in.
{
  device.name = "CHANGEME";
  device.abi = "$abi";

  apps.fdroid.packages = [
$(for p in "${fdroid[@]}"; do echo "    \"$p\""; done)
  ];

$(for p in "${release[@]}"; do echo "  apps.release.\"$p\".github = \"OWNER/REPO\"; # TODO"; done)

  apps.attended = [
$(for p in "${attended[@]}"; do echo "    \"$p\""; done)
  ];

$(for u in "${unknown[@]}"; do echo "  # unclassified: $u"; done)

  apps.cleanup = "none";
}
EOF
