#!/usr/bin/env bash
# android-rebuild import — nixos-generate-config for phones. READ-ONLY.
# Reads a connected device's structured package state and emits a starter
# device.nix on stdout. Every third-party package starts as attended; installer
# evidence is emitted only as commented source-curation hints.
set -euo pipefail

serial=${ANDROID_SERIAL:-}
snapshot_out=
while [ $# -gt 0 ]; do
  case $1 in
  --serial)
    [ $# -ge 2 ] || { echo "--serial requires a value" >&2; exit 2; }
    serial=$2; shift 2
    ;;
  --snapshot-out)
    [ $# -ge 2 ] || { echo "--snapshot-out requires a value" >&2; exit 2; }
    snapshot_out=$2; shift 2
    ;;
  *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -n "$serial" ] || { echo "import requires --serial SERIAL (or ANDROID_SERIAL)" >&2; exit 2; }
adb=(adb -s "$serial")

umask 077
work=$(mktemp -d "${TMPDIR:-/tmp}/nix-android-import.XXXXXX")
trap 'rm -rf -- "$work"' EXIT

model=$("${adb[@]}" shell getprop ro.product.model | tr -d '\r')
product=$("${adb[@]}" shell getprop ro.product.device | tr -d '\r')
abi=$("${adb[@]}" shell getprop ro.product.cpu.abi | tr -d '\r')
sdk=$("${adb[@]}" shell getprop ro.build.version.sdk | tr -d '\r')
security_patch=$("${adb[@]}" shell getprop ro.build.version.security_patch | tr -d '\r')
model_comment=$(printf %s "$model" | tr '\r\n' '  ')
abi_nix=$(jq -Rn --arg value "$abi" '$value')
"${adb[@]}" exec-out dumpsys package --proto > "$work/package.pb"
"${adb[@]}" shell pm list packages -3 --user 0 | tr -d '\r' > "$work/third-party.txt"
python3 "$NIX_ANDROID_SRC/scripts/package-snapshot.py" \
  --proto "$work/package.pb" \
  --third-party "$work/third-party.txt" \
  --model "$model" \
  --product "$product" \
  --abi "$abi" \
  --sdk "$sdk" \
  --security-patch "$security_patch" \
  > "$work/snapshot.json"

if [ -n "$snapshot_out" ]; then
  snapshot_dir=$(dirname -- "$snapshot_out")
  [ -d "$snapshot_dir" ] || { echo "snapshot directory does not exist: $snapshot_dir" >&2; exit 2; }
  snapshot_tmp=$(mktemp "$snapshot_out.tmp.XXXXXX")
  cp -- "$work/snapshot.json" "$snapshot_tmp"
  mv -- "$snapshot_tmp" "$snapshot_out"
fi

fdroid=() release=() attended=()
while IFS=$'\t' read -r pkg installer; do
  attended+=("$pkg")
  case $installer in
  org.fdroid.fdroid | org.fdroid.basic | com.looker.droidify | com.machiav3lli.fdroid)
    fdroid+=("$pkg") ;;
  dev.imranr.obtainium | dev.imranr.obtainium.fdroid)
    release+=("$pkg") ;;
  esac
done < <(jq -r '.packages[] | select(.thirdPartyForManagedUser) |
  [.name, (.installerName // "")] | @tsv' "$work/snapshot.json")

cat <<EOF
# Generated by android-rebuild import from a read-only package snapshot.
# Observed device model: $model_comment
# CURATE BEFORE CONVERGING. Notes:
#  - Every observed third-party app is attended, so this starter config can
#    assert presence without pretending installer attribution proves a source.
#  - The commented candidates below are evidence for manual curation only.
{
  device.name = "CHANGEME";
  device.abi = $abi_nix;

  apps.attended = [
$(for p in "${attended[@]}"; do printf '    %s\n' "$(jq -Rn --arg value "$p" '$value')"; done)
  ];

  apps.cleanup = "none";

  # Candidate main-F-Droid installs; verify repository and signing source:
$(for p in "${fdroid[@]}"; do echo "  # $p"; done)
  # Candidate Obtainium installs; recover the upstream URL from Obtainium:
$(for p in "${release[@]}"; do echo "  # $p"; done)
}
EOF
