#!/usr/bin/env python3
"""Render a normalized nix-android snapshot as conservative starter Nix."""

import argparse
import json
import re
from pathlib import Path


PACKAGE_NAME = re.compile(r"[A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)+")
FDROID_INSTALLERS = {
    "org.fdroid.fdroid",
    "org.fdroid.basic",
    "com.looker.droidify",
    "com.machiav3lli.fdroid",
}
OBTAINIUM_INSTALLERS = {
    "dev.imranr.obtainium",
    "dev.imranr.obtainium.fdroid",
}
PLAY_INSTALLER = "com.android.vending"


def nix_list(values, indent="    "):
    return "\n".join(f"{indent}{json.dumps(value)}" for value in values)


def comments(values):
    return "\n".join(f"  # {value}" for value in values)


def render(snapshot):
    if snapshot.get("schemaVersion") != 1:
        raise ValueError("unsupported nix-android snapshot schema")
    device = snapshot.get("device", {})
    abi = device.get("abi")
    if abi not in {"arm64-v8a", "armeabi-v7a", "x86_64"}:
        raise ValueError(f"unsupported device ABI: {abi!r}")
    model = str(device.get("model", "unknown")).replace("\r", " ").replace("\n", " ")

    packages = []
    for package in snapshot.get("packages", []):
        if not package.get("thirdPartyForManagedUser"):
            continue
        name = package.get("name")
        if not isinstance(name, str) or not PACKAGE_NAME.fullmatch(name):
            raise ValueError(f"invalid Android package name in snapshot: {name!r}")
        packages.append((name, package.get("installerName")))
    packages.sort()

    play = [name for name, installer in packages if installer == PLAY_INSTALLER]
    attended = [name for name, installer in packages if installer != PLAY_INSTALLER]
    fdroid = [name for name, installer in packages if installer in FDROID_INSTALLERS]
    obtainium = [name for name, installer in packages if installer in OBTAINIUM_INSTALLERS]

    return f'''# Generated by android-rebuild import from a read-only package snapshot.
# Observed device model: {model}
# CURATE BEFORE CONVERGING. Notes:
#  - Packages recorded with Play as installer are labeled apps.play; this is
#    evidence, not verified provenance.
#  - Every other observed third-party app is attended, so this starter config
#    asserts presence without pretending installer attribution proves a source.
#  - The commented candidates below are evidence for manual curation only.
{{
  device.name = "CHANGEME";
  device.abi = {json.dumps(abi)};

  apps.play = [
{nix_list(play)}
  ];

  apps.attended = [
{nix_list(attended)}
  ];

  apps.cleanup = "none";

  # Candidate main-F-Droid installs; verify repository and signing source:
{comments(fdroid)}
  # Candidate Obtainium installs; recover the upstream URL from Obtainium:
{comments(obtainium)}
}}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("snapshot", type=Path)
    args = parser.parse_args()
    print(render(json.loads(args.snapshot.read_text())), end="")


if __name__ == "__main__":
    main()
